name: Build Docker Images for Multi-Architecture

on:
  push:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.architecture }}
        run: |
          docker buildx build --platform linux/${{ matrix.architecture }} -t pugachartem/trigonometric-server:${{ matrix.architecture }} --push .
      - name: Create and push manifest
        run: |
          docker manifest create pugachartem/trigonometric-server:latest \
            --amend pugachartem/trigonometric-server:amd64 \
            --amend pugachartem/trigonometric-server:arm64
          docker manifest push pugachartem/trigonometric-server:latest
